#! /bin/bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

PANEL_HEIGHT=18
FONT1="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
FONT2="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-iso10646-1"

# For determining individual monitor bar geometries (positioning)
CUR_X_OFFSET=0

bspc config bottom_padding $PANEL_HEIGHT

. ~/.config/bspwm/panel/panel_colors

# Adapted from:
# https://github.com/neeasade/dotfiles/blob/master/bspwm/.config/bspwm/panel/panel
while read -r mon; do
    # Remove existing panel fifos and create new ones
    [ -e "$PANEL_FIFO$mon" ] && rm "$PANEL_FIFO$mon"
    mkfifo "$PANEL_FIFO$mon"

    # Only show bspc control info for the monitor this panel is on
    bspc control --subscribe |\
        grep -oE "[Mm]$mon[^TM]*[TML]" --line-buffered |\
        while read line; do echo W$line; done \
            > "$PANEL_FIFO$mon" &

    xtitle -sf 'T%s' > "$PANEL_FIFO$mon" &
    clock -sf 'S%a %d %b %H:%M' > "$PANEL_FIFO$mon" &
    conky -c ~/.config/bspwm/panel/conkyrc > "$PANEL_FIFO$mon" &

    # Grep out current monitor width
    CUR_MON_WIDTH=$(bspc query -T -m $mon | grep -oE "[0-9]{2,6}" | head -n 1)

    # Create the panel with the proper geometry/positioning
    # -b flag docks the bar at the bottom of the screen
    cat "$PANEL_FIFO$mon" | panel_bar | lemonbar -b -g ${CUR_MON_WIDTH}x${PANEL_HEIGHT}+${CUR_X_OFFSET}+0 -f "$FONT1" -f "$FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

    # Update the offset
    CUR_X_OFFSET=$(expr $CUR_X_OFFSET + $CUR_MON_WIDTH )
done <<< $"$(bspc query -M)"

wait
