#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PANEL_HEIGHT=18
FONT1="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
FONT2="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-iso10646-1"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %d %b %H:%M' > "$PANEL_FIFO" &
conky -c ~/.config/bspwm/panel/conkyrc > "$PANEL_FIFO" &

. ~/.config/bspwm/panel/panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$FONT1" -f "$FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
