#!/bin/bash


sudo apt-get update
sudo apt-get upgrade

sudo apt-get install dos2unix
sudo apt-get install ffmpeg
sudo apt-get install tmux

# Browsers
sudo apt-get remove iceweasel
sudo apt-get install chromium

# Cleanup
sudo apt-get autoremove
