#!/bin/bash


sudo apt-get update
sudo apt-get upgrade

sudo apt-get install dos2unix ffmpeg tmux kupfer -y

# Browsers
sudo apt-get remove iceweasel -y
sudo apt-get install chromium -y

# Cleanup
sudo apt-get autoremove -y
