#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

brew install tree
brew install nmap
brew install gpg
brew install dos2unix
brew install git
brew install ffmpeg

# Requires that you do:
# export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
brew install curl-ca-bundle

# Necessary for Vim Plugins
brew install ctags

# Necessary for markdown2evernote
brew install multimarkdown

# Remove outdated versions from the cellar
brew cleanup
