#!/bin/bash

# So brew linking works.
sudo chown -R $USER /usr/local/include
sudo chown -R $USER /usr/local/lib

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

brew install tree
brew install nmap
brew install gpg
brew install dos2unix
brew install git
brew install ffmpeg --with-fdk-aac --with-ffplay --with-freetype --with-frei0r --with-libass --with-libvo-aacenc --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools

# tmux (with vim copy paste support)
brew install tmux
brew install reattach-to-user-namespace --wrap-pbcopy-pbpaste && brew link reattach-to-user-namespace

# Requires that you do:
# export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
brew install curl-ca-bundle

# Necessary for Vim Plugins
brew install ctags

# Necessary for markdown2evernote
brew install multimarkdown

# Mutt for email
brew install mutt
brew install w3m
brew install urlview
brew install pandoc
brew install aspell

# Fast searching with The Silver Searcher (ag)
brew install the_silver_searcher

# Remove outdated versions from the cellar
brew cleanup
