#!/bin/bash

# If Git is not installed...
tput setaf 4
echo "Checking for Git..."
tput sgr0
if [[ ! "$(type -P git)" ]]; then
	tput setaf 5
	echo "Installing Git"
	tput sgr0
	brew install git
	brew link --overwrite git
else
	tput setaf 2
  echo "Git found! Moving on..."
	tput sgr0
fi

# Configure Git
# Requires your SSH keys!
tput setaf 5
read -p "Do you want to setup Github SSH access? (y/n) " -n 1
tput sgr0
if [[ ! -f ~/.ssh/id_rsa && ! -f ~/.ssh/id_rsa.pub ]]; then
	echo "Now we need to configure git a bit."
	tput setaf 5
	echo "What's your git email?"
	tput sgr0
	read email
	tput setaf 5
	echo "What's your git name? Use your full name."
	tput sgr0
	read name
	echo "\n[user]\n\temail = $email\n\tname = $name" >> ~/.gitconfig

	# To bypass some symlink issues. Maybe too brute.
	brew link --overwrite git

	# So we can push without logging in
	ssh -vT git@github.com

	tput setaf 2
	echo "gitconfig updated. Moving on..."
	tput sgr0
else
	tput setaf 3
	echo "No SSH keys found, skipping Git config..."
	echo "You can set this up later with init/git."
	tput sgr0
fi
