#!/bin/bash

if [[ ! "$(type -P grunt)" ]]; then
	tput setaf 5
	echo "Installing Grunt (grunt-cli)..."
	tput sgr0

	npm -g install grunt-cli
else
  tput setaf 2
  echo "Grunt found! Moving on..."
  tput sgr0
fi

if [[ ! "$(type -P bower)" ]]; then
	tput setaf 5
	echo "Installing Bower..."
	tput sgr0

	npm -g install bower
else
  tput setaf 2
  echo "Bower found! Moving on..."
  tput sgr0
fi

if [[ ! "$(type -P yo)" ]]; then
	tput setaf 5
	echo "Installing Yeoman..."
	tput sgr0

	npm -g install yo
else
  tput setaf 2
  echo "Yeoman found! Moving on..."
  tput sgr0
fi

# For vim-instant-markdown
sudo npm -g install git+https://github.com/ftzeng/instant-markdown-d.git
