[ -n "$PS1" ] && source ~/.bash_profile

# 256 color term.
export TERM=xterm-256color

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Force colors in ElementaryOS.
force_color_prompt=yes
