[ -n "$PS1" ] && source ~/.bash_profile

# 256 color term.
export TERM=xterm-256color

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

PERL_MB_OPT="--install_base \"/Users/ftseng/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/ftseng/perl5"; export PERL_MM_OPT;
