#!/bin/sh

MESSAGE=$(cat)

# To deal with forwaded emails,
# which may have another "From" line,
# we grep for only the first match.
# The `tail +1` is a hack around broken pipe errors.
from=$(echo "$MESSAGE" | tail +1 | grep -m 1 ^"From: " | sed s/[\,\"\']//g)
regex="From: (.+) <(.+)>"

[[ "$from" =~ $regex ]]
name="${BASH_REMATCH[1]}"
email="${BASH_REMATCH[2]}"

# Slugify the name to generate the nick.
nick=$(echo "$name" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)

if ! grep -Fq "$email" $HOME/.mutt/aliases; then
    echo "alias $nick $name <$email>" >> $HOME/.mutt/aliases
fi

echo "${MESSAGE}"
