#!/bin/bash

# Add the Spotify repository.
sudo add-apt-repository "deb http://repository.spotify.com stable non-free" -y
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59

# Add the BTSync repository.
sh -c "$(curl -fsSL http://debian.yeasoft.net/add-btsync-repository.sh)"

# Add the Zeal repositories.
sudo add-apt-repository ppa:jerzy-kozera/zeal-ppa -y
sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y

# Add the Yorba daily build repository.
sudo add-apt-repository ppa:yorba/daily-builds

# Add the Netflix Desktop repository.
sudo add-apt-repository ppa:pipelight/stable -y

# Update the repositories.
sudo apt-get update

# Required for netflix-desktop.
sudo apt-get install ttf-mscorefonts-installer

# Flash player
sudo apt-get install pepperflashplugin-nonfree
sudo update-pepperflashplugin-nonfree --install

# Dependency for California calendar.
sudo apt-get install evolution-data-server

# Install some cool apps :D
# zeal      -- offline documentation
# sc        -- spreadsheet calculator
# gpick     -- colorpicker
# alacarte  -- slingshot (app launcher) customization
sudo apt-get install --no-install-recommends --yes chromium-browser deluge pidgin vlc blender gimp inkscape spotify-client btsync-gui netflix-desktop zeal sc gpick geary california

# Mutt for email.
sudo apt-get install --yes mutt w3m urlview
cp $DIR/dots/mutt/_aliases $DIR/dots/mutt/aliases
cp $DIR/dots/mutt/_auth $DIR/dots/mutt/auth
cp $DIR/dots/mutt/_signature $DIR/dots/mutt/signature
sudo ln -s $DIR/dots/mutt ~/.mutt
echo "Setup ~/.mutt/aliases, ~/.mutt/auth, and ~/.mutt/signature as needed!"

# And remove others.
sudo apt-get purge gnome-mines gnome-sudoku simple-scan transmission-gtk parole gmusicbrowser printer-driver-foo3zjs-common xfburn gnumeric abiword thunderbird orage -y

# Was having issues with Light Locker when it comes to suspending the Acer C720, so removing it.
sudo apt-get purge light-locker light-locker-settings -y

# TrueCrypt 7.1a.
cd /tmp
wget https://github.com/AuditProject/truecrypt-verified-mirror/blob/master/Linux/truecrypt-7.1a-linux-x64.tar.gz?raw=true
tar xvzf truecrypt*
./truecrypt-7.1a-setup-x64
cd $DIR

# Conky
sudo apt-get install --no-install-recommends conky-all -y
sudo ln -s $DIR/dots/conky ~/.conky
sudo ln -s ~/.conky/conkyrc ~/.conkyrc
sudo ln -s ~/.conky/conky.desktop ~/.config/autostart/conky.desktop

# HFS+ file system support.
# You can re-mount the HFS+ drives with writable access:
# sudo mount -t hfsplus -o remount,force,rw /mount/point
sudo apt-get install hfsprogs -y

# Show hidden applications in System Settings > Startup Applications.
sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop


# Disable bluetooth and hide the menubar icon.
sudo rfkill block bluetooth
mkdir ~/.config/autostart
cp /etc/xdg/autostart/blueman.desktop ~/.config/autostart
echo "Hidden=true" | tee -a ~/.config/autostart/blueman.desktop
