#! /bin/sh

bspc config border_width        1
bspc config window_gap          12
bspc config top_padding         18

#bspc monitor -d 1 2 3 4 5
#bspc monitor -d     

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config normal_border_color "#4e4e4e"
bspc config active_border_color "#fef2b3"
bspc config focused_border_color "#FBB829"
bspc config presel_border_color "#9ad0aa"
bspc config urgent_border_color "#fc6064"
bspc config focused_locked_border_color "#65d7fd"

for monitor in $(bspc query -M); do
    bspc monitor $monitor -n "$monitor" -d     
done

# Get a window name by running
# xprop | grep WM_CLASS
# and click on the window in question
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium-browser desktop=^2
bspc rule -a Geary desktop=^3
bspc rule -a California desktop=^4
bspc rule -a Scudcloud desktop=^5
bspc rule -a VirtualBox desktop=^4
bspc rule -a feh floating=on

# This must go after the rest of the config!
if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

panel &
