#! /bin/sh

bspc config border_width        1
bspc config window_gap          12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config normal_border_color "#4e4e4e"
bspc config active_border_color "#fef2b3"
bspc config focused_border_color "#f8ce7f"
bspc config presel_border_color "#9ad0aa"
bspc config urgent_border_color "#fc6064"
bspc config focused_locked_border_color "#65d7fd"

for monitor in $(bspc query -M); do
    bspc monitor $monitor -n "$monitor" -d   
done

# Get a window name by running
# xprop | grep WM_CLASS
# and click on the window in question
bspc rule -a feh state=floating
bspc rule -a gimp state=floating

# This must go after the rest of the config!
if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

panel &
