#! /bin/sh

bspc config border_width        1
bspc config window_gap          8
bspc config top_padding         18

bspc monitor -d 1 2 3 4 5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false
bspc config normal_border_color "#4e4e4e"
bspc config active_border_color "#fef2b3"
bspc config focused_border_color "#64d68a"
bspc config presel_border_color "#528ef3"
bspc config urgent_border_color "#fc6063"
bspc config focused_locked_border_color "#65d7fd"

# Get a window name by running
# xprop | grep WM_CLASS
# and click on the window in question
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium-browser desktop=^2
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Geary desktop=^3
bspc rule -a California desktop=^4
bspc rule -a Scudcloud desktop=^5
bspc rule -a feh floating=on

compton -cb &
panel &
urxvt &
