export BSPWM_TREE=/tmp/bspwm.tree
export BSPWM_HISTORY=/tmp/bspwm.history
export BSPWM_STACK=/tmp/bspwm.stack

xrdb -merge ~/.Xresources
xset +fp ~/.fonts/
xset fp rehash
unclutter -root -visible &
feh --bg-scale ~/.wallpaper.jpg &
sxhkd &
urxvt &
compton -cb &
exec ~/.config/bspwm/wm
