#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# =============== DEPENDENCIES =================================
sudo apt-get install python g++ make wget git


# =============== GIT =================================
sh ./init/git

# If Git isn't installed by now, something messed up...here's the contigency plan.
if [[ ! "$(type -P git)" ]]; then
  tput setaf 1
  echo "Git should be installed. It isn't. Aborting."
  tput sgr0
  exit 1
fi



# =============== PACKAGES =================================

tput setaf 5
echo -e "\nInstalling some more goodies..."
echo "(this may take awhile)"
tput sgr0

sh ./init/apt

tput setaf 2
echo "Package installation complete! Moving on..."
tput sgr0


# =============== RUBY & RUBYGEMS =================================
sudo apt-get install ruby rubygems ruby-dev


# =============== PYTHON & PIP =================================
tput setaf 5
echo "Installing Python2, Python3, pip, and virtualenv...."
tput sgr0

sudo apt-get install python3 python3-pip python-pip
sudo pip install virtualenv
sudo pip-3.2 install virtualenv



# =============== VIM =================================
tput setaf 5
echo "Installing Vim..."
tput sgr0

mkdir /tmp/vim && cd $_
wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2 
tar xvjf vim-7.4.tar.bz2
cd vim*
./configure --with-features=huge --enable-luainterp=yes --enable-pythoninterp=yes --enable-python3interp=yes
make && sudo make install
cd $DIR

# Copy over necessary fonts
cp "./assets/Inconsolata+for+Powerline.otf" ~/.fonts
cp "./assets/Inconsolata-dz.otf" ~/.fonts




# =============== FONT CUSTOM =================================
if [[ ! "$(type -P fontcustom)" ]]; then
  tput setaf 5
  echo "Installing fontcustom (http://fontcustom.com/)..."
  tput sgr0

  sudo apt-get install fontforge ttfautohint
  cd /tmp/
  wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/
  sudo gem install fontcustom
  cd $DIR
else
  tput setaf 2
  echo "Font Custom found! Moving on..."
  tput sgr0
fi



# =============== NODE & GRUNT =================================
if [[ ! "$(type -P node)" ]]; then
  tput setaf 5
  echo "Installing Node..."
  tput sgr0

  mkdir /tmp/nodejs && cd $_
  wget -N http://nodejs.org/dist/node-latest.tar.gz
  tar xzvf node-latest.tar.gz && cd `ls -rd node-v*`
  ./configure
  sudo make install
  cd $DIR
else
  tput setaf 2
  echo "Node found! Moving on..."
  tput sgr0
fi

sh ./init/npm


# =============== CONFIGURATION =================================

# ~~~~ CRUNCHBANG SPECIFIC ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
if [[ "$(uname -a)" == *crunchbang* ]]; then
    # Better mouse speed
    echo -e '\n## Mouse Speed\nxset m 5 10 &' >> ~/.config/openbox/autostart

    # Terminator config
    ln -s $pwd/dots/terminator ~/.config/terminator/config
fi
