#!/bin/bash

# this script's directory and up one.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# =============== DEPENDENCIES =================================
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install --no-install-recommends python g++ make wget git openssh-server libncurses5-dev -y


# =============== GIT =================================
bash ./init/git

# If Git isn't installed by now, something messed up...here's the contigency plan.
if [[ ! "$(type -P git)" ]]; then
  tput setaf 1
  echo "Git should be installed. It isn't. Aborting."
  tput sgr0
  exit 1
fi



# =============== PACKAGES =================================

tput setaf 5
echo -e "\nInstalling some more goodies..."
echo "(this may take awhile)"
tput sgr0

sudo add-apt-repository ppa:jon-severinsson/ffmpeg -y
sudo apt-get update

sudo apt-get install --no-install-recommends dos2unix ffmpeg tmux curl dnsutils -y

tput setaf 2
echo "Package installation complete! Moving on..."
tput sgr0


# =============== RUBY & RUBYGEMS =================================
sudo apt-get install ruby rubygems ruby-dev -y


# =============== PYTHON & PIP =================================
tput setaf 5
echo "Installing Python2, Python3, pip, and virtualenv...."
tput sgr0

sudo apt-get install python3 python-pip -y
sudo pip install virtualenv

sudo apt-get install python3-setuptools -y
sudo easy_install3 pip
sudo pip3 install virtualenv



# =============== FONT CUSTOM =================================
if [[ ! "$(type -P fontcustom)" ]]; then
  tput setaf 5
  echo "Installing fontcustom (http://fontcustom.com/)..."
  tput sgr0

  # In Ubuntu 12.04, which Elementary OS Luna is based off of,
  # ttfautohint must be compiled manually.
  if [[ $(cat /etc/*-release) == *"elementary OS"* ]]; then
      sudo apt-get install libfreetype6
      wget http://sourceforge.net/projects/freetype/files/ttfautohint/0.97/ttfautohint-0.97.tar.gz
      tar xvzf ttfautohint-0.97.tar.gz
      cd ttfautohint-0.97/
      ./configure
      make -s && sudo make install
  else
      sudo apt-get install ttfautohint -y
  fi

  sudo apt-get install fontforge -y
  cd /tmp/
  wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make -s && sudo mv sfnt2woff /usr/local/bin/
  sudo gem install fontcustom
  cd $DIR
else
  tput setaf 2
  echo "Font Custom found! Moving on..."
  tput sgr0
fi



# =============== NODE & GRUNT =================================
if [[ ! "$(type -P node)" ]]; then
  tput setaf 5
  echo "Installing Node..."
  tput sgr0

  mkdir /tmp/nodejs && cd $_
  wget -N http://nodejs.org/dist/node-latest.tar.gz
  tar xzvf node-latest.tar.gz && cd `ls -rd node-v*`
  ./configure
  sudo make install -s
  cd $DIR
else
  tput setaf 2
  echo "Node found! Moving on..."
  tput sgr0
fi

sudo bash ./init/npm


# =============== VIM =================================
tput setaf 5
echo "Installing Vim..."
tput sgr0

# Lua
sudo apt-get install lua5.1 liblua5.1-dev -y

# X11, allows using system clipboard with vim.
sudo apt-get install libx11-dev libxtst-dev libxt-dev libsm-dev libxpm-dev

mkdir /tmp/vim && cd $_
wget ftp://ftp.ca.vim.org/pub/vim/unix/vim-7.4.tar.bz2
tar xvjf vim-7.4.tar.bz2
cd vim*
./configure --with-features=huge --enable-luainterp=yes --enable-pythoninterp=yes --enable-python3interp=yes --enable-gui=gtk2 --with-x --with-lua-prefix=/usr
make -s && sudo make install
cd $DIR

# Overwrite vi
sudo rm /usr/bin/vi
sudo ln -s /usr/local/bin/vim /usr/bin/vi

# Copy over necessary fonts
mkdir ~/.fonts
cp "./assets/Inconsolata+for+Powerline.otf" ~/.fonts
cp "./assets/Inconsolata-dz.otf" ~/.fonts
# Rebuild font cache
fc-cache -fv

# Build vimproc
cd vim/bundle/vimproc/
make -s
cd $DIR



# =============== DISTRO-SPECIFIC SETUP =================================

if [[ $(cat /etc/*-release) == *"elementary OS"* ]]; then
    ./init/setup/elementaryos
else
    ./init/setup/xubuntu
fi


# =============== CLEANUP ===============================================
sudo apt-get autoremove -y


