#!/bin/bash



# =============== COMMAND LINE TOOLS =================================
tput setaf 4
echo "Checking for XCode Command Line Tools..."
tput sgr0

if [[ ! "$(type -P gcc)" && "$OSTYPE" =~ ^darwin ]]; then
  tput setaf 1
  echo "The XCode Command Line Tools must be installed first."
	tput sgr0

  echo "Sending you to the download page..."
  open "https://developer.apple.com/downloads/index.action?=command%20line%20tools"
  exit 1
fi



# =============== HOMEBREW =================================
if [[ ! "$(type -P brew)" ]]; then
	tput setaf 5
	echo "Installing Homebrew..."
	tput sgr0

	# Install Homebrew
	ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

else
	tput setaf 2
	echo "Homebrew found! Moving on..."
	tput sgr0
fi



# =============== GIT =================================
bash ./init/git

# If Git isn't installed by now, something messed up...here's the contigency plan.
if [[ ! "$(type -P git)" ]]; then
  tput setaf 1
  echo "Git should be installed. It isn't. Aborting."
  tput sgr0
  exit 1
fi



# =============== BREWS =================================

tput setaf 5
read -p "Do you want install some brews? (y/n) " -n 1
tput sgr0
if [[ $REPLY =~ ^[Yy]$ ]]; then
	tput setaf 5
	echo -e "\nInstalling some more Homebrew goodies..."
	echo "(this may take awhile)"
	tput sgr0

	bash ./init/brews

	tput setaf 2
	echo "Brewing complete! Moving on..."
	tput sgr0
else
	tput setaf 3
	echo -e "\nSkipping brews...\n"
	tput sgr0
fi





# =============== RVM & RUBY =================================
if [[ ! "$(type -P rvm)" ]]; then
	tput setaf 5
    # Just install dependencies,
    # actual installation is cross-platform and
    # handled in the main script.
	echo "Installing RVM dependencies..."
	tput sgr0
	brew install autoconf automake libtool libyaml libxml2 libxslt libksba openssl
fi


# =============== PYTHON & PIP =================================
tput setaf 5
echo "Installing (Homebrew) Python2, Python3, pip, and virtualenv...."
tput sgr0

brew install python 	# Brew Python includes pip
brew install python3
pip install virtualenv
pip3 install virtualenv



# =============== VIM =================================
tput setaf 5
echo "Installing MacVim as system Vim..."
tput sgr0

brew install macvim --with-features=huge --with-lua --with-python3 --override-system-vim
brew linkapps
brew link --overwrite macvim

# Copy over necessary fonts
cp "./assets/Inconsolata+for+Powerline.otf" ~/Library/Fonts
cp "./assets/Inconsolata-dz.otf" ~/Library/Fonts

# Build vimproc
cd vim/bundle/vimproc/
make
cd $DIR


# =============== XVIM =================================
tput setaf 5
read -p "Do you want install Vim bindings for XCode (XVim)? (y/n) " -n 1
tput sgr0
if [[ $REPLY =~ ^[Yy]$ ]]; then
	tput setaf 5
	echo "Installing XVim (Vim for XCode)..."
	tput sgr0

	# Install XVim (Vim for XCode)
	git clone https://github.com/JugglerShu/XVim.git
	xcodebuild -project XVim/XVim.xcodeproj
	rm -rf XVim
else
	tput setaf 3
	echo -e "\nSkipping XVim...\n"
	tput sgr0
fi



# =============== FONT CUSTOM =================================
if [[ ! "$(type -P fontcustom)" ]]; then
  tput setaf 5
  echo "Installing fontcustom (http://fontcustom.com/)..."
  tput sgr0
  brew install fontforge ttfautohint
  gem install fontcustom
else
  tput setaf 2
  echo "Font Custom found! Moving on..."
  tput sgr0
fi



# =============== NODE & GRUNT =================================
if [[ ! "$(type -P node)" ]]; then
  tput setaf 5
  echo "Installing Node..."
  tput sgr0

  brew install node
else
  tput setaf 2
  echo "Node found! Moving on..."
  tput sgr0
fi

bash ./init/npm



# =============== TERMINAL =================================
tput setaf 5
echo -e "\nConfiguring Terminal..."
tput sgr0

cp ./assets/com.apple.Terminal.plist ~/Library/Preferences/


# =============== IRC ======================================

# Install stuff for Freenode SASL
#for i in 'Crypt::OpenSSL::Bignum' 'Crypt::DH' 'Crypt::Blowfish' 'Math::BigInt' ; do sudo perl -MCPAN -e shell <<< "install $i" ; done

brew install weechat --with-python --with-perl
brew install bitlbee

# Setup ca-certificates for OSX.
wget http://curl.haxx.se/download/curl-7.38.0.tar.gz -O /tmp/curl.tgz
cd /tmp
tar -xzvf curl.tgz
cd curl-*/lib
./mk-ca-bundle.pl
sudo mkdir -p /etc/ssl/certs/
sudo mv ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
cd $DIR



# =============== OSX SETUP  =================================
if [[ "$OSTYPE" =~ ^darwin ]]; then
  tput setaf 5
  read -p "Since you're running OSX, do you want to do some additional setup? This is a good idea for a fresh install. (y/n) " -n 1
  tput sgr0
  if [[ $REPLY =~ ^[Yy]$ ]]; then
		tput setaf 2
    echo -e "\nOk, running .osx"
		tput sgr0

    sudo bash ./init/setup/osx
  else
		tput setaf 4
    echo -e "\nOk, skipping..."
		tput sgr0
  fi 
fi
